### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Sha-mu** [yudianzheng/SketchVideo#3]
Unexpected error occurred:
 'Namespace' object has no attribute 'text'
Traceback (most recent call last):
  File "painterly_rendering.py", line 589, in <module>
    configs_to_save = main(args)
  File "painterly_rendering.py", line 176, in main
    if args.text == "None":
AttributeError: 'Namespace' object has no attribute 'text'

when i run operate_clipavideo.sh

**Comment by yudianzheng** [comment]
> Unexpected error occurred: 'Namespace' object has no attribute 'text' Traceback (most recent call last): File "painterly_rendering.py", line 589, in configs_to_save = main(args) File "painterly_rendering.py", line 176, in main if args.text == "None": AttributeError: 'Namespace' object has no attribute 'text'
> 
> when i run operate_clipavideo.sh

I have reorganized code, solving this error. You can follow the README
